### ISSUE TITLE
You can replace crudini and filter_harmless with awk

### ISSUE THREAD

**Issue by nolanl** [igorlogius/unattended-flatpak-upgrades#1]
```
awk '/\[(Extra Data|Application|Runtime|Instance)\]/ {ign=1; next} /\[.+\]/ {ign=0} ign!=1 {print}'
```

**Comment by nolanl** [comment]
Alternately you can keep the existing format by replacing crudini with:
```
awk '/^\[.+\]$/ {grp=$line; next} /./ {print grp,$line}'
```

and I think filter_harmless can be replaced with:
```
egrep -v '\[(Extra Data|Application|Runtime|Instance)\]'
```
Though, again, I don't think it is safe to ignore Application...

**Comment by igorlogius** [comment]
@nolanl 
Those statements look perfect. 
I'll try to incorperate them.

Or do you maybe want to make a pull request?

**Comment by nolanl** [comment]
I see you already switched to awk, cool. I ended up with this:
https://github.com/nolanl/null-de/blob/d4e52d16fb11cf3e77673073265a548425838ca7/update-flatpak

which also sends a notification if there are running flatpaks that need to be restarted. Please feel free to borrow that part if you find it useful.

**Comment by igorlogius** [comment]
@nolanl 
Awesome suggestion!
I added your "running-outdated detection" idea.   
Letting the user know that he might still be running outdated software is definitely useful. 
Thanks for sharing.
